export const weatherConditions = {
	clear: [ 'clear', 'ясно', 'ясна', 'bezchmurnie' ],
	cloudy: [ 'cloudy', 'облачно', 'воблачна', 'pochmurnie' ],
	drizzle: [ 'drizzle', 'изморось', 'імжа', 'mżawka' ],
	flurries: [ 'flurries', 'порывы ветра', 'шквал', 'porywy wiatru' ],
	fog: [ 'fog', 'туман', 'туман', 'mgła' ],
	fog_light: [ 'fog light', 'легкий туман', 'лёгкі туман', 'zamglenie' ],
	freezing_drizzle: [ 'freezing drizzle', 'ледяной дождь', 'ледзяны дождж', 'marznąca mżawka' ],
	freezing_rain: [ 'freezing rain', 'ледяной дождь', 'ледзяны дождж', 'marznący deszcz' ],
	freezing_rain_heavy: [ 'freezing rain heavy', 'сильный ледяной дождь', 'моцны ледзяны дождж', 'marznący deszcz' ],
	freezing_rain_light: [ 'freezing rain light', 'слабый ледяной дождь', 'слабы ледзяны дождж', 'marznący deszcz' ],
	ice_pellets: [ 'ice pellets', 'град', 'град', 'grad' ],
	ice_pellets_heavy: [ 'ice pellets heavy', 'сильный град', 'моцны град', 'mocny grad' ],
	ice_pellets_light: [ 'ice pellets light', 'слабый град', 'слабы град', 'słaby grad' ],
	mostly_clear: [ 'mostly clear', 'преимущественно ясно', 'пераважна ясна', 'w większości jasne' ],
	mostly_cloudy: [ 'mostly cloudy', 'в основном облачно', 'пераважна воблачна', 'przeważnie pochmurno' ],
	partly_cloudy: [ 'partly cloudy', 'переменная облачность', 'пераменная воблачнасць', 'częściowe zachmurzenie' ],
	rain: [ 'rain', 'дождь', 'дождж', 'deszcz' ],
	rain_heavy: [ 'rain heavy', 'сильный дождь', 'моцны дождж', 'ulewny deszcz' ],
	rain_light: [ 'rain light', 'слабый дождь', 'слабы дождж', 'światło deszczu' ],
	snow: [ 'snow', 'снег', 'снег', 'śnieg' ],
	snow_heavy: [ 'snow heavy', 'снегопад', 'снегапад', 'intensywne opady śniegu' ],
	snow_light: [ 'snow light', 'слабый снег', 'слабы снег', 'słaby śnieg ' ],
	tstorm: [ 'storm', 'гроза', 'навальніца', 'burza' ]
};
